### ISSUE TITLE
Mission, Mailmate

### ISSUE THREAD

**Issue by AlecKinnear** [ccgus/letters#9]
My guess is that Letters fell by the wayside as MailMate appeared. Benny Kjær Nielsen has done a great job of recreating that Eudora vibe, with a simple yet flexible IMAP email client which respects privacy. Editing in Mailmate revolves around Markdown which is the fastest way to write simple text for the internet.

What are you using as an email client these days Gus?

**Comment by ccgus** [comment]
I guess I should close out this repository!

I'm using Apple Mail these days.
